// export const TextColor = "#05c46b"
export const TextColor = "#ecf0f1"
export const BackgroundColor = "#1c1e21"
export const PrimaryColor = "#1e272e"
export const LightPrimaryColor = "#323b42"
export const SecondaryColor = "#05c46b"
export const LightSecondaryColor = "#c6ffda"
export const LogoColor = "#05c46b"
export const FadedTextColor = "#576574"
export const FadedSecondaryColor = "#038347"
export const Fadedx2SecondaryColor = "#02552e"
export const LogoutColor = "#e74c3c"
export const LoginColor = "#3498db"
export const TagColor = "#0652DD"
export const ErrorColor = "#e74c3c";
export const FadedErrorColor = "#ea8685";
export const AccentColor = "#f9ca24";
export const FadedAccentColor = "#e1b12c";